### ISSUE TITLE
indy_vdr occasionally does not import correctly

### ISSUE THREAD

**Issue by nrempel** [bcgov/indy-tails-server#6]
```
======== Running on http://0.0.0.0:6543 ========
(Press CTRL+C to quit)
2020-06-03 07:52:53,836 indy_vdr.bindings WARNING Library not loaded from python package
2020-06-03 07:52:56,631 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/indy/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/indy/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/indy/tails_server/web.py", line 72, in put_file
    genesis_txn_bytes, revocation_reg_id, storage_path
  File "/home/indy/tails_server/ledger.py", line 38, in get_rev_reg_def
    req = indy_vdr.ledger.build_get_revoc_reg_def_request(
AttributeError: module 'indy_vdr.ledger' has no attribute 'build_get_revoc_reg_def_request'
```

**Comment by nrempel** [comment]
There was a problem with the docker image dependency `von-image` which has been resolved: https://hub.docker.com/layers/bcgovimages/von-image/next-1/images/sha256-b1beefbdd2aacbb785c3f509c835671d428a9635dd19802014314992a87fe431?context=explore
